// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-courses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var COURSES = [
  { id: "modes-action-microorganismes", title: "Modes d'action des microorganismes", chapter: "Microbiologie", path: "/licence/sage-femme/s1/microbio/modes-action" },
  { id: "bacteries", title: "Bact\xE9ries", chapter: "Microbiologie", path: "/licence/sage-femme/s1/microbio/bacteries" },
  { id: "virus", title: "Virus", chapter: "Microbiologie", path: "/licence/sage-femme/s1/microbio/virus" },
  { id: "parasites", title: "Parasites", chapter: "Microbiologie", path: "/licence/sage-femme/s1/microbio/parasites" },
  { id: "mycetes", title: "Myc\xE8tes", chapter: "Microbiologie", path: "/licence/sage-femme/s1/microbio/mycetes" },
  { id: "hematologie", title: "H\xE9matologie", chapter: "H\xE9matologie", path: "/licence/sage-femme/s1/hematologie" },
  { id: "immunologie", title: "Immunologie", chapter: "Immunologie", path: "/licence/sage-femme/s1/immunologie" }
];
var list_courses_default = defineTool({
  name: "list_courses",
  title: "List courses",
  description: "List all available Sage-Femme S1 course pages on the portfolio (Microbiologie, H\xE9matologie, Immunologie).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(COURSES, null, 2) }],
    structuredContent: { courses: COURSES }
  })
});

// src/lib/mcp/tools/get-course-url.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var SITE = "https://reddabra.lovable.app";
var get_course_url_default = defineTool2({
  name: "get_course_url",
  title: "Get course URL",
  description: "Return the full public URL for a course by its id (see list_courses).",
  inputSchema: {
    id: z.string().min(1).describe("Course id from list_courses (e.g. 'virus', 'hematologie').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const course = COURSES.find((c) => c.id === id);
    if (!course) {
      return { content: [{ type: "text", text: `Unknown course id: ${id}` }], isError: true };
    }
    const url = `${SITE}${course.path}`;
    return {
      content: [{ type: "text", text: url }],
      structuredContent: { ...course, url }
    };
  }
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_contact_default = defineTool3({
  name: "get_contact",
  title: "Get contact",
  description: "Get contact information for Pr. Rkia EDDABRA (ISPITS Agadir).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Pr. Rkia EDDABRA",
      role: "MCH \u2014 ISPITS Agadir",
      email: "eddabrarkia@gmail.com",
      site: "https://reddabra.lovable.app"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "eddabra-portfolio-mcp",
  title: "Pr. Rkia EDDABRA \u2014 Portfolio MCP",
  version: "0.1.0",
  instructions: "Tools for the Pr. Rkia EDDABRA academic portfolio (ISPITS Agadir). Use `list_courses` to discover Sage-Femme S1 course pages, `get_course_url` to resolve a course id to its public URL, and `get_contact` for contact information.",
  tools: [list_courses_default, get_course_url_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
